services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\ArchivePalettesBundle\:
    resource: '../src/{EventListener}/*'

  HeimrichHannot\ArchivePalettesBundle\Manager\ArchivePalettesManager:
    public: true
    autoconfigure: false


